# Generated by Django 6.0.6 on 2026-06-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('Date', models.DateField(max_length=10)),
                ('Capacity', models.IntegerField(verbose_name=10)),
            ],
        ),
    ]
