# Generated by Django 6.0.6 on 2026-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_capacity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightcapacity',
            name='Capacity',
            field=models.IntegerField(),
        ),
    ]
